version: "3"

services:
  server:
    container_name: server
    build: .
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      CONNECTION_STRING: "host=todo_db user=postgres password=postgres dbname=postgres sslmode=disable"
    depends_on:
      - todo_db
    networks:
      - todo

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  todo_db:
    image: postgres
    container_name: todo_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todo
  
volumes:
  pgdata:
  prometheus_data:
  grafana-storage:


networks:
  todo:
    driver: bridge