version: "3"
services:
  todo-server-test:
    container_name: todo-test
    build: 
      context: .
      dockerfile: Dockerfile.test
      no_cache: true
    ports:
      - "8001:8001"
    environment:
      CONNECTION_STRING: "host=test_db user=test password=test dbname=test sslmode=disable"
      JWT_SECRET_KEY: "test"
      LOG_LEVEL: "-4"
    depends_on:
      - test-db
    networks:
      - todo-test

  test-db:
    image: postgres
    container_name: test-db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    restart: on-failure
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - /tmp:/tmp
    networks:
      - todo-test

networks:
  todo-test:
    driver: bridge
